SOURCES=../lib/github.com/shwestrick/sml-matrix-market/**.sml ../lib/github.com/shwestrick/sml-matrix-market/**.mlb **.mlb **.sml

main.mlton: $(SOURCES)
	mlton main.mlton.mlb

main.mpl: $(SOURCES)
	mpl main.mpl.mlb
